#!/bin/bash

cd $(dirname "$0")
cd ..

cp devinstall/precomtocopy .git/hooks/pre-commit
git submodule init src/gargamel
git submodule update src/gargamel

git submodule init src/testing/testsuite
git submodule update src/testing/testsuite

mkdir intermediate
cd src
find * -type d -exec mkdir ../intermediate/\{\} \;

